In [5]:
import pandas as pd
movies=pd.read_csv("data/bollywood_movies.csv")

movies.head(20)

         id                        title    year  rating
0    872906                        Jawan  2023.0     7.3
1    554600     Uri: The Surgical Strike  2019.0     7.2
2    781732                       Animal  2023.0     7.4
3    975533                  The Archies  2023.0     7.1
4    734253                    Adipurush  2023.0     5.3
5     19404  Dilwale Dulhania Le Jayenge  1995.0     8.5
6     20453                     3 Idiots  2009.0     8.0
7    720557                      Tiger 3  2023.0     5.9
8     10757     Kabhi Khushi Kabhie Gham  2001.0     7.7
9     26022              My Name Is Khan  2010.0     8.1
10  1211409          Kya Masti Kya Dhoom  2023.0     0.0
11     7508          Like Stars on Earth  2007.0     8.0
12   864692                      Pathaan  2023.0     6.6
13     4251                   Veer-Zaara  2004.0     7.4
14   205022              Chennai Express  2013.0     6.5
15   592508                 Sooryavanshi  2021.0     5.8
16    11518                  Mohabbatein  2000.0     7.0
17    11854           Kuch Kuch Hota Hai  1998.0     7.5
18   534780                    Andhadhun  2018.0     7.6
19   950071                   Jaane Jaan  2023.0     7.0

In [6]:
movies.shape

(7419, 4)

In [7]:
movies.isnull().sum()

id          0
title       0
year      353
rating      0
dtype: int64

In [8]:
movies.dropna(inplace=True)

In [9]:
movies.shape

(7066, 4)

In [10]:
movies.duplicated().sum()

np.int64(0)

In [11]:
movies['tags']= movies['year'] + movies['rating']

In [12]:
movies.head(20)

         id                        title    year  rating    tags
0    872906                        Jawan  2023.0     7.3  2030.3
1    554600     Uri: The Surgical Strike  2019.0     7.2  2026.2
2    781732                       Animal  2023.0     7.4  2030.4
3    975533                  The Archies  2023.0     7.1  2030.1
4    734253                    Adipurush  2023.0     5.3  2028.3
5     19404  Dilwale Dulhania Le Jayenge  1995.0     8.5  2003.5
6     20453                     3 Idiots  2009.0     8.0  2017.0
7    720557                      Tiger 3  2023.0     5.9  2028.9
8     10757     Kabhi Khushi Kabhie Gham  2001.0     7.7  2008.7
9     26022              My Name Is Khan  2010.0     8.1  2018.1
10  1211409          Kya Masti Kya Dhoom  2023.0     0.0  2023.0
11     7508          Like Stars on Earth  2007.0     8.0  2015.0
12   864692                      Pathaan  2023.0     6.6  2029.6
13     4251                   Veer-Zaara  2004.0     7.4  2011.4
14   205022              Chennai Express  2013.0     6.5  2019.5
15   592508                 Sooryavanshi  2021.0     5.8  2026.8
16    11518                  Mohabbatein  2000.0     7.0  2007.0
17    11854           Kuch Kuch Hota Hai  1998.0     7.5  2005.5
18   534780                    Andhadhun  2018.0     7.6  2025.6
19   950071                   Jaane Jaan  2023.0     7.0  2030.0

In [13]:
movies.columns

Index(['id', 'title', 'year', 'rating', 'tags'], dtype='object')

In [14]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7066 entries, 0 to 7418
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      7066 non-null   int64
 1   title   7066 non-null   object
 2   year    7066 non-null   float64
 3   rating  7066 non-null   float64
 4   tags    7066 non-null   float64
dtypes: float64(3), int64(1), object(1)
memory usage: 331.2+ KB

In [15]:
movies.describe()

                 id         year       rating         tags
count  7.066000e+03  7066.000000  7066.000000  7066.000000
mean   5.188429e+05  1997.956977     3.436159  2001.393136
std    3.407178e+05    22.052941     3.319424    22.822426
min    4.800000e+02  1913.000000     0.000000  1913.000000
25%    2.688802e+05  1983.250000     0.000000  1986.000000
50%    4.633710e+05  2004.000000     4.000000  2008.400000
75%    8.012785e+05  2017.000000     6.300000  2020.000000
max    1.218599e+06  2026.000000    10.000000  2033.000000

In [16]:
movies.sort_values(by='rating', ascending=False).head(10)

           id               title    year  rating    tags
5496   331566  Insaaf Kaun Karega  1984.0    10.0  1994.0
2708  1091609         Dada Lakhmi  2022.0    10.0  2032.0
3076   276863              Hitler  1998.0    10.0  2008.0
6992   557127             Chuskit  2019.0    10.0  2029.0
3082    60042        Ashok Chakra  2010.0    10.0  2020.0
3114   869313         Zakhmi Sher  1984.0    10.0  1994.0
3137   316660           Raja Saab  1969.0    10.0  1979.0
3146   418621               Fuddu  2016.0    10.0  2026.0
3151   410266           Taaqatwar  1989.0    10.0  1999.0
6962   588147       Kashmir Daily  2018.0    10.0  2028.0

In [17]:
movies[movies['title']=="Jawan"]

       id  title    year  rating    tags
0  872906  Jawan  2023.0     7.3  2030.3

In [18]:
movies['tags']=movies['title']

In [19]:
from sklearn.feature_extraction.text import CountVectorizer

In [20]:
cv=CountVectorizer(max_features=5000,stop_words='english')

In [21]:
vectors=cv.fit_transform(movies['tags'].values.astype('U')).toarray()

In [22]:
vectors.shape

(7066, 5000)

In [23]:
from sklearn.metrics.pairwise import cosine_similarity

In [24]:
similarity=cosine_similarity(vectors)

In [25]:
similarity.shape

(7066, 7066)

In [26]:
movies[movies['title']=="Jawan"].index[0]

np.int64(0)

In [27]:
list(enumerate(similarity[0]))[0:5]

[(0, np.float64(1.0)),
 (1, np.float64(0.0)),
 (2, np.float64(0.0)),
 (3, np.float64(0.0)),
 (4, np.float64(0.0))]

In [28]:
movies['tags']=movies['title']

In [29]:
movies['tags']=movies['title']+" "+movies['year'].astype(str)

In [30]:
vectors=cv.fit_transform(movies['tags'].values.astype('U')).toarray()

In [31]:
similarity=cosine_similarity(vectors)

In [32]:
list(enumerate(similarity[0]))[0:10]

[(0, np.float64(0.9999999999999998)),
 (1, np.float64(0.0)),
 (2, np.float64(0.4999999999999999)),
 (3, np.float64(0.4999999999999999)),
 (4, np.float64(0.4999999999999999)),
 (5, np.float64(0.0)),
 (6, np.float64(0.0)),
 (7, np.float64(0.4999999999999999)),
 (8, np.float64(0.0)),
 (9, np.float64(0.0))]

In [33]:
distances=similarity[0]

In [34]:
movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]

In [35]:
for i in movies_list:
    print(movies.iloc[i[0]].title)

Majbooriyan
Khufiya
Joram
Bholaa
Award

In [36]:
movies[movies['title']=="Animal"].index[0]

np.int64(2)

In [37]:
list(enumerate(similarity[2]))[0:10]

[(0, np.float64(0.4999999999999999)),
 (1, np.float64(0.0)),
 (2, np.float64(0.9999999999999998)),
 (3, np.float64(0.4999999999999999)),
 (4, np.float64(0.4999999999999999)),
 (5, np.float64(0.0)),
 (6, np.float64(0.0)),
 (7, np.float64(0.4999999999999999)),
 (8, np.float64(0.0)),
 (9, np.float64(0.0))]

In [38]:
distances=similarity[2]

In [39]:
movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]

In [40]:
for i in movies_list:
    print(movies.iloc[i[0]].title)

Majbooriyan
Khufiya
Joram
Bholaa
Award

In [41]:
import os
print(os.getcwd())

D:\MovieProject\movie recommendation system

In [42]:
import pickle

pickle.dump(movies, open('artificats/movie_list.pkl', 'wb'))
pickle.dump(similarity, open('artificats/similarity.pkl', 'wb'))